name: Frontend CI pipeline

on:
  push:
    branches:
      - master
    paths: "skillswipe/**"
  pull_request:
    branches:
      - master
    paths: "skillswipe/**"

concurrency:
  # For pull requests, cancel all currently-running jobs for this workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
  GIT_COMMIT: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: skillswipe/node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('skillswipe/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        working-directory: ./skillswipe
        run: npm ci --prefer-offline --no-audit

      - name: Run lint check
        working-directory: ./skillswipe
        run: npm run lint:ci
        continue-on-error: false

      - name: Build project
        working-directory: ./skillswipe
        run: |
          node -v
          npm -v
          npm run build

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: skillswipe/node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('skillswipe/package-lock.json') }}

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Tests with coverage
        working-directory: ./skillswipe
        run:
          npm run test:ci

          ############ old

      # - name: Use Node.js 19.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 19.x
      #     cache: "npm"
      #     cache-dependency-path: skillswipe/package-lock.json

      # - name: Install npm dependencies
      #   working-directory: ./skillswipe
      #   run: npm ci

      # - name: Lint code
      #   working-directory: ./skillswipe
      #   run: npm run lint

      # - name: Build
      #   working-directory: ./skillswipe
      #   run: npm run build

      # - name: Run tests with coverage
      #   working-directory: ./skillswipe
      #   run: npm run test:ci
