name: Backend CI pipeline

on:
  push:
    branches:
      - master
    paths: "backend/**"
  pull_request:
    branches:
      - master
    paths: "backend/**"

concurrency:
  # For pull requests, cancel all currently-running jobs for this workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
  GIT_COMMIT: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('backend/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        working-directory: ./backend
        run: npm ci --prefer-offline --no-audit

      - name: Run lint check
        working-directory: ./backend
        run: npm run lint:ci
        continue-on-error: false

      - name: Build project
        working-directory: ./backend
        run: |
          node -v
          npm -v
          npm run build

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('backend/package-lock.json') }}

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Tests with coverage
        working-directory: ./backend
        run: npm run test:cov
