name: Frontend CI pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cope repository
        uses: actions/checkout@v3

      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: 'npm'
          cache-dependency-path: skillswipe/package-lock.json

      - name: Install npm dependencies
        working-directory: ./skillswipe
        run: npm ci

      - name: Lint code
        working-directory: ./skillswipe
        run: npm run lint

      - name: Build
        working-directory: ./skillswipe
        run: npm run build

      - name: Run tests with coverage
        working-directory: ./skillswipe
        run: npm run test:ci

      # - name: Check test coverage
      #   working-directory: ./skillswipe
      #   run: npm run test:cov
