name: Backend CI pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      node-version: 19.x

    steps:
      - name: Cope repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ node-version }}

      - name: Install npm dependencies
        working-directory: ./backend
        run: |
          cp .env.testing .env
          npm ci

      - name: Lint code
        working-directory: ./backend
        run: npm run lint:ci

      - name: Build
        working-directory: ./backend
        run: npm run build

      - name: Run tests
        working-directory: ./backend
        run: npm run test

      - name: Check test coverage
        working-directory: ./backend
        run: npm run test:cov
